toolbar:
  - bold italic underline strikethrough blockquote | undo redo | paste link image media
plugins:
  - link
  - paste
  - image
  - media
menubar: false
statusbar: false
language: "hu_HU"
max_width : 800
min_width : 300
min_height : 150
default_link_target: "_blank"
image_description: false
media_poster: false
media_alt_source: false
content_style: "p {font-family: Arial, Helvetica, sans-serif;font-size: 16px;margin:0;padding:0;}"
